# Generated by Django 2.2.3 on 2019-07-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='rpc_user',
            new_name='rpc_username',
        ),
        migrations.AddField(
            model_name='transaction',
            name='node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='txs', related_query_name='tx', to='cryptocurrency.Node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(choices=[('BTC', 'BTC')], max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('rpc_username', 'rpc_password', 'rpc_host', 'rpc_port')},
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('node', 'txid')},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
    ]
