# Generated by Django 2.2.3 on 2019-07-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_auto_20190708_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='received',
        ),
        migrations.AlterField(
            model_name='node',
            name='rpc_port',
            field=models.IntegerField(help_text='Listen for JSON-RPC connections on this port', verbose_name='RPC port'),
        ),
    ]
