# Generated by Django 2.2.3 on 2019-07-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0004_auto_20190709_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='confirmations_number',
            new_name='min_confirmations',
        ),
    ]
