# Generated by Django 2.2.3 on 2019-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0005_auto_20190709_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ts_received',
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.PositiveIntegerField(default=0, help_text='transaction creation time in timestamp', verbose_name='time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp_received',
            field=models.PositiveIntegerField(default=0, help_text='transaction receipt time in timestamp', verbose_name='receipt time'),
            preserve_default=False,
        ),
    ]
