# Generated by Django 2.2.3 on 2019-07-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0006_auto_20190710_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('BTC', 'Bitcoin')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='rpc_port',
            field=models.PositiveIntegerField(help_text='Listen for JSON-RPC connections on this port', verbose_name='RPC port'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('rpc_host', 'rpc_port')},
        ),
    ]
